// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rudolfoborges/rbpay/messages/stock.proto

package rudolfoborges.rbpay.messages;

public final class StockProtos {
  private StockProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StockAdjustmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rudolfoborges.rbpay.messages.StockAdjustment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string product = 1;</code>
     */
    java.lang.String getProduct();
    /**
     * <code>optional string product = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductBytes();

    /**
     * <code>optional double amount = 2;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code rudolfoborges.rbpay.messages.StockAdjustment}
   */
  public  static final class StockAdjustment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rudolfoborges.rbpay.messages.StockAdjustment)
      StockAdjustmentOrBuilder {
    // Use StockAdjustment.newBuilder() to construct.
    private StockAdjustment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StockAdjustment() {
      product_ = "";
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private StockAdjustment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              product_ = s;
              break;
            }
            case 17: {

              amount_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_StockAdjustment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.class, rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.Builder.class);
    }

    public static final int PRODUCT_FIELD_NUMBER = 1;
    private volatile java.lang.Object product_;
    /**
     * <code>optional string product = 1;</code>
     */
    public java.lang.String getProduct() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        product_ = s;
        return s;
      }
    }
    /**
     * <code>optional string product = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductBytes() {
      java.lang.Object ref = product_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        product_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUNT_FIELD_NUMBER = 2;
    private double amount_;
    /**
     * <code>optional double amount = 2;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProductBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, product_);
      }
      if (amount_ != 0D) {
        output.writeDouble(2, amount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProductBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, product_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, amount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rudolfoborges.rbpay.messages.StockProtos.StockAdjustment)) {
        return super.equals(obj);
      }
      rudolfoborges.rbpay.messages.StockProtos.StockAdjustment other = (rudolfoborges.rbpay.messages.StockProtos.StockAdjustment) obj;

      boolean result = true;
      result = result && getProduct()
          .equals(other.getProduct());
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rudolfoborges.rbpay.messages.StockProtos.StockAdjustment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rudolfoborges.rbpay.messages.StockAdjustment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rudolfoborges.rbpay.messages.StockAdjustment)
        rudolfoborges.rbpay.messages.StockProtos.StockAdjustmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_StockAdjustment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.class, rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.Builder.class);
      }

      // Construct using rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        product_ = "";

        amount_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor;
      }

      public rudolfoborges.rbpay.messages.StockProtos.StockAdjustment getDefaultInstanceForType() {
        return rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.getDefaultInstance();
      }

      public rudolfoborges.rbpay.messages.StockProtos.StockAdjustment build() {
        rudolfoborges.rbpay.messages.StockProtos.StockAdjustment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rudolfoborges.rbpay.messages.StockProtos.StockAdjustment buildPartial() {
        rudolfoborges.rbpay.messages.StockProtos.StockAdjustment result = new rudolfoborges.rbpay.messages.StockProtos.StockAdjustment(this);
        result.product_ = product_;
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rudolfoborges.rbpay.messages.StockProtos.StockAdjustment) {
          return mergeFrom((rudolfoborges.rbpay.messages.StockProtos.StockAdjustment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rudolfoborges.rbpay.messages.StockProtos.StockAdjustment other) {
        if (other == rudolfoborges.rbpay.messages.StockProtos.StockAdjustment.getDefaultInstance()) return this;
        if (!other.getProduct().isEmpty()) {
          product_ = other.product_;
          onChanged();
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rudolfoborges.rbpay.messages.StockProtos.StockAdjustment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rudolfoborges.rbpay.messages.StockProtos.StockAdjustment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object product_ = "";
      /**
       * <code>optional string product = 1;</code>
       */
      public java.lang.String getProduct() {
        java.lang.Object ref = product_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          product_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductBytes() {
        java.lang.Object ref = product_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          product_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder setProduct(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        product_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder clearProduct() {
        
        product_ = getDefaultInstance().getProduct();
        onChanged();
        return this;
      }
      /**
       * <code>optional string product = 1;</code>
       */
      public Builder setProductBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        product_ = value;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <code>optional double amount = 2;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>optional double amount = 2;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double amount = 2;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:rudolfoborges.rbpay.messages.StockAdjustment)
    }

    // @@protoc_insertion_point(class_scope:rudolfoborges.rbpay.messages.StockAdjustment)
    private static final rudolfoborges.rbpay.messages.StockProtos.StockAdjustment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rudolfoborges.rbpay.messages.StockProtos.StockAdjustment();
    }

    public static rudolfoborges.rbpay.messages.StockProtos.StockAdjustment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StockAdjustment>
        PARSER = new com.google.protobuf.AbstractParser<StockAdjustment>() {
      public StockAdjustment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new StockAdjustment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StockAdjustment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StockAdjustment> getParserForType() {
      return PARSER;
    }

    public rudolfoborges.rbpay.messages.StockProtos.StockAdjustment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AvailableAmountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:rudolfoborges.rbpay.messages.AvailableAmount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double amount = 1;</code>
     */
    double getAmount();
  }
  /**
   * Protobuf type {@code rudolfoborges.rbpay.messages.AvailableAmount}
   */
  public  static final class AvailableAmount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rudolfoborges.rbpay.messages.AvailableAmount)
      AvailableAmountOrBuilder {
    // Use AvailableAmount.newBuilder() to construct.
    private AvailableAmount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AvailableAmount() {
      amount_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AvailableAmount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              amount_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_AvailableAmount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.class, rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private double amount_;
    /**
     * <code>optional double amount = 1;</code>
     */
    public double getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (amount_ != 0D) {
        output.writeDouble(1, amount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, amount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof rudolfoborges.rbpay.messages.StockProtos.AvailableAmount)) {
        return super.equals(obj);
      }
      rudolfoborges.rbpay.messages.StockProtos.AvailableAmount other = (rudolfoborges.rbpay.messages.StockProtos.AvailableAmount) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getAmount())
          == java.lang.Double.doubleToLongBits(
              other.getAmount()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(rudolfoborges.rbpay.messages.StockProtos.AvailableAmount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rudolfoborges.rbpay.messages.AvailableAmount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rudolfoborges.rbpay.messages.AvailableAmount)
        rudolfoborges.rbpay.messages.StockProtos.AvailableAmountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_AvailableAmount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.class, rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.Builder.class);
      }

      // Construct using rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        amount_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rudolfoborges.rbpay.messages.StockProtos.internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor;
      }

      public rudolfoborges.rbpay.messages.StockProtos.AvailableAmount getDefaultInstanceForType() {
        return rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.getDefaultInstance();
      }

      public rudolfoborges.rbpay.messages.StockProtos.AvailableAmount build() {
        rudolfoborges.rbpay.messages.StockProtos.AvailableAmount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public rudolfoborges.rbpay.messages.StockProtos.AvailableAmount buildPartial() {
        rudolfoborges.rbpay.messages.StockProtos.AvailableAmount result = new rudolfoborges.rbpay.messages.StockProtos.AvailableAmount(this);
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rudolfoborges.rbpay.messages.StockProtos.AvailableAmount) {
          return mergeFrom((rudolfoborges.rbpay.messages.StockProtos.AvailableAmount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(rudolfoborges.rbpay.messages.StockProtos.AvailableAmount other) {
        if (other == rudolfoborges.rbpay.messages.StockProtos.AvailableAmount.getDefaultInstance()) return this;
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        rudolfoborges.rbpay.messages.StockProtos.AvailableAmount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (rudolfoborges.rbpay.messages.StockProtos.AvailableAmount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double amount_ ;
      /**
       * <code>optional double amount = 1;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <code>optional double amount = 1;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double amount = 1;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:rudolfoborges.rbpay.messages.AvailableAmount)
    }

    // @@protoc_insertion_point(class_scope:rudolfoborges.rbpay.messages.AvailableAmount)
    private static final rudolfoborges.rbpay.messages.StockProtos.AvailableAmount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new rudolfoborges.rbpay.messages.StockProtos.AvailableAmount();
    }

    public static rudolfoborges.rbpay.messages.StockProtos.AvailableAmount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AvailableAmount>
        PARSER = new com.google.protobuf.AbstractParser<AvailableAmount>() {
      public AvailableAmount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AvailableAmount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AvailableAmount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AvailableAmount> getParserForType() {
      return PARSER;
    }

    public rudolfoborges.rbpay.messages.StockProtos.AvailableAmount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rudolfoborges_rbpay_messages_StockAdjustment_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rudolfoborges_rbpay_messages_AvailableAmount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(rudolfoborges/rbpay/messages/stock.pro" +
      "to\022\034rudolfoborges.rbpay.messages\"2\n\017Stoc" +
      "kAdjustment\022\017\n\007product\030\001 \001(\t\022\016\n\006amount\030\002" +
      " \001(\001\"!\n\017AvailableAmount\022\016\n\006amount\030\001 \001(\001B" +
      "+\n\034rudolfoborges.rbpay.messagesB\013StockPr" +
      "otosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rudolfoborges_rbpay_messages_StockAdjustment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rudolfoborges_rbpay_messages_StockAdjustment_descriptor,
        new java.lang.String[] { "Product", "Amount", });
    internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rudolfoborges_rbpay_messages_AvailableAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rudolfoborges_rbpay_messages_AvailableAmount_descriptor,
        new java.lang.String[] { "Amount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
